# Generated by Django 2.2.4 on 2023-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.IntegerField()),
                ('videoUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
